services:
  - type: web
    name: ICPA-AGENDADOR
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: EVOLUTION_API_URL
        sync: false
      - key: REDIS_URL
        sync: false
databases:
  - name: icpa-agendador-db
    engine: postgres
    version: "13"
